<?php

namespace NNP\PlatformBundle\Repository;

/**
 * CategorieNdemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieNdemRepository extends \Doctrine\ORM\EntityRepository
{

}
