<?php

namespace NNP\PlatformBundle\Repository;

/**
 * NdemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NdemRepository extends \Doctrine\ORM\EntityRepository
{
}
