nnp_platform_homepage:
    path:     /
    defaults: { _controller: NNPPlatformBundle:Homepage:index }

nnp_platform_presentation:
    path:     /group/qui-sommes-nous
    defaults: { _controller: NNPPlatformBundle:Homepage:presentation }

nnp_platform_profil:
    path:     /mon-profil
    defaults:  
        _controller: NNPPlatformBundle:Homepage:profil 

nnp_platform_mesNdems:
    path:     /mon-profil/mes-sujets/
    defaults:  
        _controller: NNPPlatformBundle:Homepage:mesNdems 

nnp_platform_editerProfil:
    path:     /mon-profil/editer/
    defaults:  
        _controller: NNPPlatformBundle:Homepage:editerProfil 

nnp_platform_modifierPassword:
    path:     /mon-profil/modifier-password
    defaults:  
        _controller: NNPPlatformBundle:Homepage:modifierPassword

nnp_platform_creerNdem:
    path:     /mon-profil/cree-ndem
    defaults:  
        _controller: NNPPlatformBundle:Homepage:creerNdem

nnp_platform_leNdem:
    path:     /sujet/{id}
    defaults:  
        _controller: NNPPlatformBundle:Homepage:leNdem
    requirements:
        id: \d+

nnp_platform_liste:
    path:     /categorie
    defaults:  
        _controller: NNPPlatformBundle:Homepage:liste
