nnp_platform_homepage:
    path:     /
    defaults: { _controller: NNPPlatformBundle:Homepage:index }

nnp_platform_presentation:
    path:     /group/qui-sommes-nous
    defaults: { _controller: NNPPlatformBundle:Homepage:presentation }

nnp_platform_profil:
    path:     /mon-profil/{id}
    defaults:  
        _controller: NNPPlatformBundle:Homepage:profil 
    requirements:
        id: \d+

nnp_platform_editerProfil:
    path:     /mon-profil/editer/{id}
    defaults:  
        _controller: NNPPlatformBundle:Homepage:editerProfil 
    requirements:
        id: \d+

nnp_platform_creerNdem:
    path:     /mon-profil/cree-ndem
    defaults:  
        _controller: NNPPlatformBundle:Homepage:creerNdem
